/* eslint-disable */
// This file is auto-generated by scripts/sync-block-registry.ts — do not edit manually.

import type { ComponentType } from 'react'

import FooterSectionOne from '@/components/blocks/footer/footer-section-one'
import FooterSectionTwo from '@/components/blocks/footer/footer-section-two'
import ForgotPasswordOne from '@/components/blocks/auth/forgot-password-one'
import ForgotPasswordThree from '@/components/blocks/auth/forgot-password-three'
import ForgotPasswordTwo from '@/components/blocks/auth/forgot-password-two'
import HeaderOne from '@/components/blocks/header/header-one'
import HeaderTwo from '@/components/blocks/header/header-two'
import HeroSectionFour from '@/components/blocks/hero-section/hero-section-four'
import HeroSectionOne from '@/components/blocks/hero-section/hero-section-one'
import HeroSectionThree from '@/components/blocks/hero-section/hero-section-three'
import HeroSectionTwo from '@/components/blocks/hero-section/hero-section-two'
import LogoCloudOne from '@/components/blocks/logo-cloud/logo-cloud-one'
import LogoCloudThree from '@/components/blocks/logo-cloud/logo-cloud-three'
import LogoCloudTwo from '@/components/blocks/logo-cloud/logo-cloud-two'
import SignUpOne from '@/components/blocks/auth/sign-up-one'
import SignUpTwo from '@/components/blocks/auth/sign-up-two'
import TeamsSectionFive from '@/components/blocks/teams/teams-section-five'
import TeamsSectionFour from '@/components/blocks/teams/teams-section-four'
import TeamsSectionOne from '@/components/blocks/teams/teams-section-one'
import TeamsSectionThree from '@/components/blocks/teams/teams-section-three'
import TeamsSectionTwo from '@/components/blocks/teams/teams-section-two'
import TestamonialSectionOne from '@/components/blocks/testamonials/testamonial-section-one'

import { defineBlock } from './define-block'
import type { BlockDefinition, BlockRegistryEntry } from './types'

function entry(definition: BlockDefinition, Component: ComponentType): BlockRegistryEntry {
  return { definition, Component }
}

export const blockRegistryEntries: BlockRegistryEntry[] = [
  entry(
    defineBlock({
      slug: 'footer-section-one',
      title: 'Footer Section One',
      description: '',
      category: 'footer',
      tags: ['footer', 'footer'],
      sourceFiles: [{ path: 'components/blocks/footer/footer-section-one.tsx', language: 'tsx' }],
    }),
    FooterSectionOne,
  ),
  entry(
    defineBlock({
      slug: 'footer-section-two',
      title: 'Footer Section Two',
      description: '',
      category: 'footer',
      tags: ['footer', 'footer'],
      sourceFiles: [{ path: 'components/blocks/footer/footer-section-two.tsx', language: 'tsx' }],
    }),
    FooterSectionTwo,
  ),
  entry(
    defineBlock({
      slug: 'forgot-password-one',
      title: 'Forgot Password One',
      description: '',
      category: 'auth',
      tags: ['auth', 'auth'],
      sourceFiles: [{ path: 'components/blocks/auth/forgot-password-one.tsx', language: 'tsx' }],
    }),
    ForgotPasswordOne,
  ),
  entry(
    defineBlock({
      slug: 'forgot-password-three',
      title: 'Forgot Password Three',
      description: '',
      category: 'auth',
      tags: ['auth', 'auth'],
      sourceFiles: [{ path: 'components/blocks/auth/forgot-password-three.tsx', language: 'tsx' }],
    }),
    ForgotPasswordThree,
  ),
  entry(
    defineBlock({
      slug: 'forgot-password-two',
      title: 'Forgot Password Two',
      description: '',
      category: 'auth',
      tags: ['auth', 'auth'],
      sourceFiles: [{ path: 'components/blocks/auth/forgot-password-two.tsx', language: 'tsx' }],
    }),
    ForgotPasswordTwo,
  ),
  entry(
    defineBlock({
      slug: 'header-one',
      title: 'Header One',
      description: '',
      category: 'header',
      tags: ['header', 'header'],
      sourceFiles: [{ path: 'components/blocks/header/header-one.tsx', language: 'tsx' }],
    }),
    HeaderOne,
  ),
  entry(
    defineBlock({
      slug: 'header-two',
      title: 'Header Two',
      description: '',
      category: 'header',
      tags: ['header', 'header'],
      sourceFiles: [{ path: 'components/blocks/header/header-two.tsx', language: 'tsx' }],
    }),
    HeaderTwo,
  ),
  entry(
    defineBlock({
      slug: 'hero-section-four',
      title: 'Hero Section Four',
      description: '',
      category: 'hero',
      tags: ['hero-section', 'hero'],
      sourceFiles: [{ path: 'components/blocks/hero-section/hero-section-four.tsx', language: 'tsx' }],
    }),
    HeroSectionFour,
  ),
  entry(
    defineBlock({
      slug: 'hero-section-one',
      title: 'Hero Section One',
      description: '',
      category: 'hero',
      tags: ['hero-section', 'hero'],
      sourceFiles: [{ path: 'components/blocks/hero-section/hero-section-one.tsx', language: 'tsx' }],
    }),
    HeroSectionOne,
  ),
  entry(
    defineBlock({
      slug: 'hero-section-three',
      title: 'Hero Section Three',
      description: '',
      category: 'hero',
      tags: ['hero-section', 'hero'],
      sourceFiles: [{ path: 'components/blocks/hero-section/hero-section-three.tsx', language: 'tsx' }],
    }),
    HeroSectionThree,
  ),
  entry(
    defineBlock({
      slug: 'hero-section-two',
      title: 'Hero Section Two',
      description: '',
      category: 'hero',
      tags: ['hero-section', 'hero'],
      sourceFiles: [{ path: 'components/blocks/hero-section/hero-section-two.tsx', language: 'tsx' }],
    }),
    HeroSectionTwo,
  ),
  entry(
    defineBlock({
      slug: 'logo-cloud-one',
      title: 'Logo Cloud One',
      description: '',
      category: 'logo-cloud',
      tags: ['logo-cloud', 'logo-cloud'],
      sourceFiles: [{ path: 'components/blocks/logo-cloud/logo-cloud-one.tsx', language: 'tsx' }],
    }),
    LogoCloudOne,
  ),
  entry(
    defineBlock({
      slug: 'logo-cloud-three',
      title: 'Logo Cloud Three',
      description: '',
      category: 'logo-cloud',
      tags: ['logo-cloud', 'logo-cloud'],
      sourceFiles: [{ path: 'components/blocks/logo-cloud/logo-cloud-three.tsx', language: 'tsx' }],
    }),
    LogoCloudThree,
  ),
  entry(
    defineBlock({
      slug: 'logo-cloud-two',
      title: 'Logo Cloud Two',
      description: '',
      category: 'logo-cloud',
      tags: ['logo-cloud', 'logo-cloud'],
      sourceFiles: [{ path: 'components/blocks/logo-cloud/logo-cloud-two.tsx', language: 'tsx' }],
    }),
    LogoCloudTwo,
  ),
  entry(
    defineBlock({
      slug: 'sign-up-one',
      title: 'Sign Up One',
      description: '',
      category: 'auth',
      tags: ['auth', 'auth'],
      sourceFiles: [{ path: 'components/blocks/auth/sign-up-one.tsx', language: 'tsx' }],
    }),
    SignUpOne,
  ),
  entry(
    defineBlock({
      slug: 'sign-up-two',
      title: 'Sign Up Two',
      description: '',
      category: 'auth',
      tags: ['auth', 'auth'],
      sourceFiles: [{ path: 'components/blocks/auth/sign-up-two.tsx', language: 'tsx' }],
    }),
    SignUpTwo,
  ),
  entry(
    defineBlock({
      slug: 'teams-section-five',
      title: 'Teams Section Five',
      description: '',
      category: 'teams',
      tags: ['teams', 'teams'],
      sourceFiles: [{ path: 'components/blocks/teams/teams-section-five.tsx', language: 'tsx' }],
    }),
    TeamsSectionFive,
  ),
  entry(
    defineBlock({
      slug: 'teams-section-four',
      title: 'Teams Section Four',
      description: '',
      category: 'teams',
      tags: ['teams', 'teams'],
      sourceFiles: [{ path: 'components/blocks/teams/teams-section-four.tsx', language: 'tsx' }],
    }),
    TeamsSectionFour,
  ),
  entry(
    defineBlock({
      slug: 'teams-section-one',
      title: 'Teams Section One',
      description: '',
      category: 'teams',
      tags: ['teams', 'teams'],
      sourceFiles: [{ path: 'components/blocks/teams/teams-section-one.tsx', language: 'tsx' }],
    }),
    TeamsSectionOne,
  ),
  entry(
    defineBlock({
      slug: 'teams-section-three',
      title: 'Teams Section Three',
      description: '',
      category: 'teams',
      tags: ['teams', 'teams'],
      sourceFiles: [{ path: 'components/blocks/teams/teams-section-three.tsx', language: 'tsx' }],
    }),
    TeamsSectionThree,
  ),
  entry(
    defineBlock({
      slug: 'teams-section-two',
      title: 'Teams Section Two',
      description: '',
      category: 'teams',
      tags: ['teams', 'teams'],
      sourceFiles: [{ path: 'components/blocks/teams/teams-section-two.tsx', language: 'tsx' }],
    }),
    TeamsSectionTwo,
  ),
  entry(
    defineBlock({
      slug: 'testamonial-section-one',
      title: 'Testamonial Section One',
      description: '',
      category: 'testamonials',
      tags: ['testamonials', 'testamonials'],
      sourceFiles: [{ path: 'components/blocks/testamonials/testamonial-section-one.tsx', language: 'tsx' }],
    }),
    TestamonialSectionOne,
  ),
]
