import type { NavUIRegistryItem, RegistryPreviewSpec } from '@/registry/types'
import type { ComponentItemEntry } from '@/registry/items/components'

export const ROOT_REGISTRY_PATH = 'registry.json'
export const GENERATED_BLOCK_PREVIEWS_PATH = 'registry/generated/block-previews.generated.tsx'
export const GENERATED_COMPONENT_PREVIEWS_PATH =
  'registry/generated/component-previews.generated.tsx'
export const GENERATED_ILLUSTRATION_PREVIEWS_PATH =
  'registry/generated/illustration-previews.generated.tsx'
export const PUBLIC_REGISTRY_DIR = 'public/r'
export const REGISTRY_SCHEMA = 'https://ui.shadcn.com/schema/registry.json'
export const REGISTRY_ITEM_SCHEMA = 'https://ui.shadcn.com/schema/registry-item.json'
export const REGISTRY_NAME = 'navdeep-singh'
export const REGISTRY_HOMEPAGE = 'https://ui.navdeepsingh.dev'

export function isOutputItem(item: NavUIRegistryItem): boolean {
  return item.status === 'published' || Boolean(item.compatibilityOutput)
}

export function isCatalogItem(item: NavUIRegistryItem): boolean {
  return item.status === 'published' && item.kind !== 'support'
}

function sorted(values: string[]): string[] {
  return [...new Set(values)].sort((a, b) => a.localeCompare(b))
}

export function toShadcnRegistryItem(item: NavUIRegistryItem) {
  const description =
    item.kind === 'component' ? (item.registryDescription ?? item.description) : item.description

  const files = item.registry.files.map((file) => ({
    path: file.path,
    target: file.target,
    type: file.type,
  }))

  return {
    $schema: REGISTRY_ITEM_SCHEMA,
    name: item.registry.name,
    type: item.registry.type,
    title: item.title,
    description,
    ...(item.registry.dependencies.length > 0
      ? { dependencies: sorted(item.registry.dependencies) }
      : {}),
    ...(item.registry.registryDependencies.length > 0
      ? { registryDependencies: sorted(item.registry.registryDependencies) }
      : {}),
    files: files.sort((a, b) => a.target.localeCompare(b.target) || a.path.localeCompare(b.path)),
    meta: {
      navui: {
        status: item.status,
        kind: item.kind,
        category: item.category,
      },
    },
  }
}

export function createRootRegistry(items: NavUIRegistryItem[]) {
  return {
    $schema: REGISTRY_SCHEMA,
    name: REGISTRY_NAME,
    homepage: REGISTRY_HOMEPAGE,
    items: items
      .filter(isOutputItem)
      .sort((a, b) => a.slug.localeCompare(b.slug))
      .map(toShadcnRegistryItem),
  }
}

export function renderRootRegistry(items: NavUIRegistryItem[]): string {
  return `${JSON.stringify(createRootRegistry(items), null, 2)}\n`
}

function importName(kind: string, slug: string, suffix = ''): string {
  const pascal = slug
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
  return `${kind}${pascal}${suffix}`
}

function renderImport(name: string, preview: RegistryPreviewSpec): string {
  if (preview.exportName) {
    return `import { ${preview.exportName} as ${name} } from '${preview.module}'`
  }
  return `import ${name} from '${preview.module}'`
}

function renderPreviewMapModule(
  items: NavUIRegistryItem[],
  kind: 'block' | 'illustration',
  exportName: string,
): string {
  const imports: string[] = []
  const entries: string[] = []

  for (const item of items
    .filter((candidate) => isCatalogItem(candidate) && candidate.kind === kind)
    .sort((a, b) => a.slug.localeCompare(b.slug))) {
    if (!item.preview) continue
    const name = importName(item.kind, item.slug)
    imports.push(renderImport(name, item.preview))
    entries.push(`  '${item.slug}': ${name},`)
  }

  return `// This file is generated by scripts/registry/generate-source.ts. Do not edit manually.

import type { ComponentType } from 'react'

${imports.sort((a, b) => a.localeCompare(b)).join('\n')}

export const ${exportName}: Record<string, ComponentType> = {
${entries.join('\n')}
}
`
}

export function renderBlockPreviewModule(items: NavUIRegistryItem[]): string {
  return renderPreviewMapModule(items, 'block', 'blockPreviewComponents')
}

export function renderIllustrationPreviewModule(items: NavUIRegistryItem[]): string {
  return renderPreviewMapModule(items, 'illustration', 'illustrationPreviewComponents')
}

export function renderComponentPreviewModule(
  items: NavUIRegistryItem[],
  componentEntries: ComponentItemEntry[],
): string {
  const imports: string[] = []
  const componentEntriesOutput: string[] = []

  for (const item of items
    .filter((candidate) => isCatalogItem(candidate) && candidate.kind === 'component')
    .sort((a, b) => a.slug.localeCompare(b.slug))) {
    if (!item.preview) continue
    const name = importName(item.kind, item.slug)
    imports.push(renderImport(name, item.preview))
    componentEntriesOutput.push(`  '${item.slug}': ${name},`)
  }

  const exampleEntries: string[] = []
  for (const entry of componentEntries) {
    if (entry.definition.status !== 'published') continue
    for (const example of entry.examples) {
      const name = importName('Example', entry.definition.slug, importName('', example.id))
      imports.push(renderImport(name, { module: example.previewModule }))
      exampleEntries.push(`  '${entry.definition.slug}:${example.id}': ${name},`)
    }
  }

  return `// This file is generated by scripts/registry/generate-source.ts. Do not edit manually.

import type { ComponentType } from 'react'

${imports.sort((a, b) => a.localeCompare(b)).join('\n')}

export const componentPreviewComponents: Record<string, ComponentType> = {
${componentEntriesOutput.join('\n')}
}

export const componentExamplePreviewComponents: Record<string, ComponentType> = {
${exampleEntries.join('\n')}
}
`
}

export function expectedPublicOutputNames(items: NavUIRegistryItem[]): string[] {
  return ['registry', ...items.filter(isOutputItem).map((item) => item.slug)].sort((a, b) =>
    a.localeCompare(b),
  )
}
