import { promises as fs } from 'node:fs'
import path from 'node:path'

const ROOT = process.cwd()
const DEPRECATED_SOURCE_DIRECTORIES = [
  'app',
  'components',
  'data',
  'hooks',
  'lib',
  'registry',
  'site',
] as const
const SOURCE_EXTENSIONS = new Set(['.ts', '.tsx', '.mts', '.mjs'])
const OLD_IMPORT_PATTERN =
  /^@\/(?:site|data|hooks|components\/ui\/components|components\/showcase|components\/pages|components\/kibo-ui|lib\/(?:analytics|github|portfolio-search-data|search-data|block-source|registry))(?:\/|$)/
const IMPORT_PATTERN = /(?:from\s+|import\s*\()["']([^"']+)["']/g

async function exists(relativePath: string) {
  try {
    await fs.access(path.join(ROOT, relativePath))
    return true
  } catch {
    return false
  }
}

async function sourceFiles(directory: string): Promise<string[]> {
  const absoluteDirectory = path.join(ROOT, directory)
  const entries = await fs.readdir(absoluteDirectory, { withFileTypes: true })
  const files: string[] = []

  for (const entry of entries) {
    const relativePath = path.posix.join(directory, entry.name)
    if (entry.isDirectory()) {
      files.push(...(await sourceFiles(relativePath)))
    } else if (SOURCE_EXTENSIONS.has(path.extname(entry.name))) {
      files.push(relativePath)
    }
  }

  return files
}

function importsFrom(source: string) {
  const imports: string[] = []
  for (const match of source.matchAll(IMPORT_PATTERN)) imports.push(match[1])
  return imports
}

function isRegistryImplementation(relativePath: string) {
  if (!relativePath.startsWith('src/registry/')) return false
  if (relativePath.includes('/generated/')) return false
  if (/\.(?:demo|item|file|test)\.tsx?$/.test(relativePath)) return false
  if (relativePath.endsWith('.item.ts') || relativePath.endsWith('.file.ts')) return false
  return /src\/registry\/(?:blocks|components|illustrations)\//.test(relativePath)
}

const errors: string[] = []

for (const directory of DEPRECATED_SOURCE_DIRECTORIES) {
  if (await exists(directory)) {
    errors.push(`${directory}/ is deprecated; application source belongs under src/.`)
  }
}

const files = await sourceFiles('src')
for (const relativePath of files) {
  const source = await fs.readFile(path.join(ROOT, relativePath), 'utf8')
  const imports = importsFrom(source)

  for (const specifier of imports) {
    if (OLD_IMPORT_PATTERN.test(specifier)) {
      errors.push(`${relativePath} imports deprecated source path "${specifier}".`)
    }

    if (isRegistryImplementation(relativePath)) {
      if (specifier.includes('.demo') || specifier.includes('/previews/')) {
        errors.push(`${relativePath} registry implementation imports demo code "${specifier}".`)
      }
      if (specifier.startsWith('@/app') || specifier.startsWith('@/features/')) {
        errors.push(
          `${relativePath} registry implementation imports application code "${specifier}".`,
        )
      }
    }

    if (
      relativePath.startsWith('src/features/portfolio/') &&
      specifier.startsWith('@/features/navui/')
    ) {
      errors.push(
        `${relativePath} crosses from portfolio into NavUI website internals "${specifier}".`,
      )
    }
  }

  if (relativePath.startsWith('src/registry/generated/')) {
    if (!source.startsWith('// This file is generated by scripts/registry/generate-source.ts.')) {
      errors.push(`${relativePath} is in the generated boundary without the generator header.`)
    }
  }
}

if (errors.length > 0) {
  console.error(`\n[architecture:validate] ${errors.length} error(s):`)
  for (const error of errors) console.error(`  ✗ ${error}`)
  process.exit(1)
}

console.log(
  `[architecture:validate] OK — ${files.length} source file(s), no deprecated paths or boundary violations.`,
)
