/**
 * Scans `components/blocks/<folder>/*.tsx` and regenerates
 * `registry/block-registry.generated.tsx` with static imports.
 *
 * Run via `bun run sync:blocks` (also runs before dev/build).
 */
import { promises as fs } from 'node:fs'
import path from 'node:path'

const ROOT = process.cwd()
const BLOCKS_DIR = path.join(ROOT, 'components/blocks')
const OUTPUT = path.join(ROOT, 'registry/block-registry.generated.tsx')

const KEBAB_TSX = /^[a-z0-9]+(?:-[a-z0-9]+)*\.tsx$/
const SUPPORT_FILE_SUFFIXES = ['-illustration.tsx']

const FOLDER_CATEGORY_MAP: Record<string, string> = {
  'hero-section': 'hero',
  header: 'header',
  featured: 'featured',
  'logo-cloud': 'logo-cloud',
  teams: 'teams',
  footer: 'footer',
}

function humanizeSlug(slug: string): string {
  return slug
    .split('-')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

function toImportName(slug: string): string {
  return slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function resolveCategory(folder: string, slug: string): string {
  if (slug.startsWith('forgot-password-')) return 'forgot-password'
  if (slug.startsWith('sign-up-')) return 'sign-up'
  return FOLDER_CATEGORY_MAP[folder] ?? folder
}

type DiscoveredBlock = {
  folder: string
  slug: string
  sourcePath: string
  importPath: string
  importName: string
  category: string
}

async function discoverBlocks(): Promise<DiscoveredBlock[]> {
  const folders = await fs.readdir(BLOCKS_DIR, { withFileTypes: true })
  const blocks: DiscoveredBlock[] = []
  const seenSlugs = new Set<string>()

  for (const dirent of folders) {
    if (!dirent.isDirectory()) continue
    const folder = dirent.name
    const folderPath = path.join(BLOCKS_DIR, folder)

    try {
      await fs.access(path.join(folderPath, 'registry.json'))
    } catch {
      continue
    }

    const files = await fs.readdir(folderPath)

    for (const filename of files.sort()) {
      if (!KEBAB_TSX.test(filename)) continue
      if (SUPPORT_FILE_SUFFIXES.some((suffix) => filename.endsWith(suffix))) continue
      const slug = filename.replace(/\.tsx$/, '')
      if (seenSlugs.has(slug)) continue
      seenSlugs.add(slug)

      blocks.push({
        folder,
        slug,
        sourcePath: `components/blocks/${folder}/${filename}`,
        importPath: `@/components/blocks/${folder}/${filename.replace(/\.tsx$/, '')}`,
        importName: toImportName(slug),
        category: resolveCategory(folder, slug),
      })
    }
  }

  return blocks.sort((a, b) => a.slug.localeCompare(b.slug))
}

function renderFile(blocks: DiscoveredBlock[]): string {
  const imports = blocks.map((b) => `import ${b.importName} from '${b.importPath}'`).join('\n')

  const entries = blocks
    .map((b) => {
      const title = humanizeSlug(b.slug)
      return `  entry(
    defineBlock({
      slug: '${b.slug}',
      title: '${title}',
      description: '',
      category: '${b.category}',
      tags: ['${b.folder}', '${b.category}'],
      sourceFiles: [{ path: '${b.sourcePath}', language: 'tsx' }],
    }),
    ${b.importName},
  ),`
    })
    .join('\n')

  return `/* eslint-disable */
// This file is auto-generated by scripts/sync-block-registry.ts — do not edit manually.

import type { ComponentType } from 'react'

${imports}

import { defineBlock } from './define-block'
import type { BlockDefinition, BlockRegistryEntry } from './types'

function entry(definition: BlockDefinition, Component: ComponentType): BlockRegistryEntry {
  return { definition, Component }
}

export const blockRegistryEntries: BlockRegistryEntry[] = [
${entries}
]
`
}

async function main() {
  const blocks = await discoverBlocks()
  const contents = renderFile(blocks)
  await fs.writeFile(OUTPUT, contents, 'utf8')
  console.log(
    `[sync:blocks] Registered ${blocks.length} block(s) → registry/block-registry.generated.tsx`,
  )
}

main().catch((error) => {
  console.error('[sync:blocks] Failed:', error)
  process.exit(1)
})
